export const ADD_NAME = 'ADD_NAME';
export const TOGGLE_LOADING = 'TOGGLE_LOADING';
// hard code for now
export const TOGGLE_SUCCESS_POPUP = 'TOGGLE_SUCCESS_POPUP';
export const TOGGLE_ERROR_POPUP = 'TOGGLE_ERROR_POPUP';
export const TOGGLE_OPERATION_POPUP = 'TOGGLE_OPERATION_POPUP';

export const SET_SUCCESS_MESSAGE = 'SET_SUCCESS_MESSAGE';
export const SET_ERROR_MESSAGE = 'SET_ERROR_MESSAGE';
export const SET_OPERATION_MESSAGE = 'SET_OPERATION_MESSAGE';
export const SET_USER_INFO = 'SET_USER_INFO';
export const SET_BASE_USER = 'SET_BASE_USER';
export const SET_TOKEN = 'SET_TOKEN';
export const SET_ERROR_CALLBACK = 'SET_ERROR_CALLBACK';
export const SET_SUCCESS_CALLBACK = 'SET_SUCCESS_CALLBACK';
export const SET_OPERATION_CALLBACK = 'SET_OPERATION_CALLBACK';
